// @generated
// This file was automatically generated and should not be edited.

@_exported import ApolloAPI

public struct AnnotationParts: PocketGraph.SelectionSet, Fragment {
  public static var fragmentDefinition: StaticString { """
    fragment AnnotationParts on SavedItem {
      __typename
      annotations {
        __typename
        highlights {
          __typename
          id
          version
          quote
          patch
          _createdAt
          _updatedAt
        }
      }
    }
    """ }

  public let __data: DataDict
  public init(data: DataDict) { __data = data }

  public static var __parentType: ParentType { PocketGraph.Objects.SavedItem }
  public static var __selections: [Selection] { [
    .field("annotations", Annotations?.self),
  ] }

  /// Annotations associated to this SavedItem
  public var annotations: Annotations? { __data["annotations"] }

  /// Annotations
  ///
  /// Parent Type: `SavedItemAnnotations`
  public struct Annotations: PocketGraph.SelectionSet {
    public let __data: DataDict
    public init(data: DataDict) { __data = data }

    public static var __parentType: ParentType { PocketGraph.Objects.SavedItemAnnotations }
    public static var __selections: [Selection] { [
      .field("highlights", [Highlight?]?.self),
    ] }

    /// User-highlighted passages on a SavedItem
    public var highlights: [Highlight?]? { __data["highlights"] }

    /// Annotations.Highlight
    ///
    /// Parent Type: `Highlight`
    public struct Highlight: PocketGraph.SelectionSet {
      public let __data: DataDict
      public init(data: DataDict) { __data = data }

      public static var __parentType: ParentType { PocketGraph.Objects.Highlight }
      public static var __selections: [Selection] { [
        .field("id", ID.self),
        .field("version", Int.self),
        .field("quote", String.self),
        .field("patch", String.self),
        .field("_createdAt", Timestamp.self),
        .field("_updatedAt", Timestamp.self),
      ] }

      /// The ID for this Highlight annotation
      public var id: ID { __data["id"] }
      /// Version number for highlight data specification
      public var version: Int { __data["version"] }
      /// The full text of the highlighted passage. Used as a fallback for
      /// rendering highlight if the patch fails.
      public var quote: String { __data["quote"] }
      /// Patch string generated by 'DiffMatchPatch' library, serialized
      /// into text via `patch_toText` method. Use `patch_fromText` to
      /// deserialize into an object that can be used by the DiffMatchPatch
      /// library. Format is similar to UniDiff but is character-based.
      /// The patched text depends on version. For example, the version 2
      /// patch surrounds the highlighted text portion with a pair of
      /// sentinel tags: '<pkt_tag_annotation></pkt_tag_annotation>'
      /// Reference: https://github.com/google/diff-match-patch
      public var patch: String { __data["patch"] }
      /// When the Highlight was created
      public var _createdAt: Timestamp { __data["_createdAt"] }
      /// When the highlight was last updated
      public var _updatedAt: Timestamp { __data["_updatedAt"] }
    }
  }
}
