// @generated
// This file was automatically generated and should not be edited.

@_exported import ApolloAPI

public struct TagParts: PocketGraph.SelectionSet, Fragment {
  public static var fragmentDefinition: StaticString {
    #"fragment TagParts on Tag { __typename name id }"#
  }

  public let __data: DataDict
  public init(_dataDict: DataDict) { __data = _dataDict }

  public static var __parentType: ApolloAPI.ParentType { PocketGraph.Objects.Tag }
  public static var __selections: [ApolloAPI.Selection] { [
    .field("__typename", String.self),
    .field("name", String.self),
    .field("id", PocketGraph.ID.self),
  ] }

  /// The actual tag string the user created for their list
  public var name: String { __data["name"] }
  /// Surrogate primary key. This is usually generated by clients, but will be generated by the server if not passed through creation
  public var id: PocketGraph.ID { __data["id"] }

  public init(
    name: String,
    id: PocketGraph.ID
  ) {
    self.init(_dataDict: DataDict(
      data: [
        "__typename": PocketGraph.Objects.Tag.typename,
        "name": name,
        "id": id,
      ],
      fulfilledFragments: [
        ObjectIdentifier(TagParts.self)
      ]
    ))
  }
}
