// @generated
// This file was automatically generated and should not be edited.

@_exported import ApolloAPI

public struct TagParts: PocketGraph.SelectionSet, Fragment {
  public static var fragmentDefinition: StaticString { """
    fragment TagParts on Tag {
      __typename
      name
      id
    }
    """ }

  public let __data: DataDict
  public init(data: DataDict) { __data = data }

  public static var __parentType: ParentType { PocketGraph.Objects.Tag }
  public static var __selections: [Selection] { [
    .field("name", String.self),
    .field("id", ID.self),
  ] }

  /// The actual tag string the user created for their list
  public var name: String { __data["name"] }
  /// Surrogate primary key. This is usually generated by clients, but will be generated by the server if not passed through creation
  public var id: ID { __data["id"] }
}
