fragment NotesPart on Note {
    contentPreview
    docMarkdown
    createdAt
    id
    savedItem {
      id
    }
    source
    title
    updatedAt
    archived
    deleted
}

query Note($noteId: ID!) {
  note(id: $noteId) {
    __typename
    ...NotesPart
  }
}

query Notes($pagination: PaginationInput, $filter: NoteFilterInput) {
  notes(pagination: $pagination, filter: $filter) {
    edges {
      cursor
      node {
        __typename
        ...NotesPart

      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    totalCount
  }
}


mutation CreateNoteMarkdown($input: CreateNoteMarkdownInput!) {
  createNoteMarkdown(input: $input) {
    __typename
    ...NotesPart
  }
}

mutation DeleteNote($input: DeleteNoteInput!) {
  deleteNote(input: $input)
}

mutation EditNoteContentMarkdown($input: EditNoteContentMarkdownInput!) {
  editNoteContentMarkdown(input: $input) {
    __typename
    ...NotesPart
  }
}

mutation EditNoteTitle($input: EditNoteTitleInput!) {
  editNoteTitle(input: $input) {
    __typename
    ...NotesPart
  }
}
