# File tracking the same rules as Firefox Mobile

disabled_rules: # rule identifiers to exclude from running
  # Auto-correctable rules
  - trailing_comma

  # Disabled all default rules
  - block_based_kvo
  - closure_parameter_position
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discouraged_direct_init
  - discarded_notification_center_observer
  - duplicate_imports
  - fallthrough
  - file_length
  - for_where
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - is_disjoint
  - legacy_hashing
  - legacy_random
  - line_length
  - missing_docs
  - multiple_closures_with_trailing_closure
  - nesting
  - no_fallthrough_only
  - notification_center_detachment
  - nsobject_prefer_isequal
  - orphaned_doc_comment
  - private_unit_test
  - reduce_boolean
  - redundant_string_enum_value
  - self_in_property_initialization
  - shorthand_operator
  - superfluous_disable_command
  - switch_case_alignment
  - todo
  - type_name
  - type_body_length
  - unneeded_break_in_switch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - weak_delegate
  - xctfail_message

opt_in_rules: # some rules are only opt-in
  # These rules were originally opted into. Disabling for now to get
  # Swiftlint up and running.
  # - statement_position
  # - explicit_init
  # - file_header
  # - deployment_target
  # - discouraged_optional_collection
  # - overridden_super_call
  # - prohibited_interface_builder
  # - prohibited_super_call
  # - protocol_property_accessors_order
  # - redundant_objc_attribute
  # - redundant_type_annotation
  # Find all the available rules by running:
  # swiftlint rules
  - anyobject_protocol
  - array_init
  - attributes
  - capture_variable
  - closing_brace
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - duplicate_imports
  - duplicate_enum_cases
  - multiline_arguments_brackets
  - multiline_arguments
  - opening_brace
  - return_arrow_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - build
  - .build
  - PocketKit/.build
  - PocketKit/Sources/Sync/API.swift
  - DerivedData/
  - PocketKit/Sources/PocketGraph/
# reporter: "json" # reporter type (xcode, json, csv, checkstyle)
reporter: 'xcode' # reporter type (xcode, json, csv, checkstyle)
