---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
  - push_branch: main
    pipeline: app-store-pipeline
  - pull_request_target_branch: '*'
    pipeline: qa-build-test-pipeline

pipelines:
  # Will create a QA Build and run a test across multiple simulator devices
  qa-build-test-pipeline:
    stages:
      # Build a qa build, and build a test build in parallel
      - build-and-test: {}
      # Run multiple tests on simulators in parallel
      - run-test-groups: {}
      - deploy-test-results: {}
  # Will create an app store build and upload it to itunes connect
  app-store-pipeline:
    stages:
      # First Build the release build (app store build)
      - release-build: {}
      # Run the steps to deploy to the app store
      - deploy-app-store: {}
  # Will create an app store capabale build, but release it to Internal Testing users in Testflight.
  # Intended to run nightly.
  nightly-internal-pipeline:
    stages:
      # First Build the release build (app store build)
      - release-build: {}
      # Run the steps to deploy to testflight internally
      - deploy-internal-testflight: {}
stages:
  build-and-test:
    workflows:
      # Build a test build
      - test-build: {}
      # Build a qa build
      - qa-build: {}

  run-test-groups:
    workflows:
      - run-tests-unit: {}
      - run-tests-ui-1: {}
      - run-tests-ui-2: {}
      - run-tests-ui-3: {}

  deploy-test-results:
    workflows:
      - deploy-test-results: {}

  release-build:
    workflows:
      - release-build: {}
  deploy-internal-testflight:
    workflows:
      - internal-testflight-release: {}
  deploy-app-store:
    workflows:
      - app-store-release: {}

workflows:
  #Reusable workflow that is ran before each workflow to setup the necessary information
  _setup:
    steps:
      - brew-install@0:
          inputs:
            - packages: swiftlint
      - activate-ssh-key@4: {}
      - git-clone@6: {}
      - certificate-and-profile-installer@1: {}
      - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_XCCONFIG_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install production secrets.xcconfig
      - resource-archive@2:
          inputs:
            - extract_to_path: '$BITRISE_SOURCE_DIR/PocketKit/Sources/Textile/Style/Typography/Fonts'
            - archive_url: '$BITRISEIO_BASE_FONTS_URL'
          title: Install fonts
      - script@1:
          title: Download latest schema
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e

                cd PocketKit
                swift package --disable-sandbox  --allow-writing-to-package-directory apollo-fetch-schema
                swift package --allow-writing-to-package-directory apollo-generate

  #Workflow to that can be ran after archiving builds to upload dysms to sentry.
  _upload_sentry:
    steps:
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e

                brew tap getsentry/tools
                brew install getsentry/tools/sentry-cli
                sentry-cli --log-level=debug --auth-token $SENTRY_AUTH_TOKEN  upload-dif -o pocket -p ios-next $BITRISE_DSYM_PATH
                #TODO: In the future we can add Sentry releases here.

  _danger:
    steps:
      - cache-pull@2: {}
      - activate-ssh-key@4: {}
      - git-clone@6: {}
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e

                echo "Run danger"
                swift run danger-swift ci
      - cache-push@2: {}

  # Helper step to pull the built test bundle.
  _pull_test_bundle:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: build-and-test.test-build

  #Builds a release build that could be uploaded to App Store Connect
  release-build:
    steps:
      - xcode-archive@4:
          title: Build an app store release build
          inputs:
            - project_path: '$BITRISE_PROJECT_PATH'
            - scheme: '$BITRISE_SCHEME'
            - distribution_method: app-store
            - configuration: RELEASE
            - xcconfig_content: CURRENT_PROJECT_VERSION = $BITRISE_BUILD_NUMBER
            - export_method: app-store
      - deploy-to-bitrise-io@2:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_IPA_PATH:BITRISE_IPA_PATH'
    before_run:
      - _setup
    after_run:
      - _upload_sentry

  # Uses artifacts from the release build stage and workflow to ship the build to testflight.
  internal-testflight-release:
    steps:
      - activate-ssh-key@4: {}
      #clone the repo so we can get our fastlane files.
      - git-clone@6: {}
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: release-build.release-build
      - fastlane@3:
          inputs:
            - connection: 'off'
            - api_key_path: '$BITRISEIO_APP_STORE_CONNECT_API_KEY_URL'
            - api_issuer: '$API_KEY_ISSUER_ID'
            - verbose_log: 'yes'
            - lane: beta_internal

  # Uses artifacts from the release build stage and workflow to ship the build to the App Store and create a github release.
  app-store-release:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: release-build.release-build
      - deploy-to-itunesconnect-deliver@2:
          inputs:
            - app_id: '$APP_ID'
            - connection: 'off'
            - api_key_path: '$BITRISEIO_APP_STORE_CONNECT_API_KEY_URL'
            - api_issuer: '$API_KEY_ISSUER_ID'
      - github-release@0:
          inputs:
            - username: '$GITHUB_RELEASE_USERNAME'
            - name: 8.0+$BITRISE_BUILD_NUMBER
            - body: '$GIT_CLONE_COMMIT_MESSAGE_SUBJECT'
            - pre_release: 'yes'
            - draft: 'no'
            - tag: 8.0+$BITRISE_BUILD_NUMBER
            - commit: '$GIT_CLONE_COMMIT_HASH'
            - api_token: '$GITHUB_RELEASE_TOKEN'
    before_run:
      - _setup
    after_run:
      - _upload_sentry

  qa-build:
    steps:
      - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_DEVELOPMENT_XCCONFIG_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install development secrets.xcconfig
      - xcode-archive@4:
          inputs:
            - xcconfig_content: |-
                COMPILER_INDEX_STORE_ENABLE = NO
                CURRENT_PROJECT_VERSION = $BITRISE_BUILD_NUMBER
            - configuration: Debug
      - deploy-to-bitrise-io@2: {}
      - slack@3:
          inputs:
            - channel: '#log-ios-qa-builds'
            - webhook_url: $SLACK_WEBHOOK_URL
    before_run:
      - _setup
    after_run:
      - _upload_sentry

  test-build:
    steps:
      - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_TEST_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install test secrets.xcconfig
      - xcode-build-for-test:
          inputs:
            - destination: generic/platform=iOS Simulator
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_TEST_BUNDLE_PATH:BITRISE_TEST_BUNDLE_PATH'
    before_run:
      - _setup

  run-tests-unit:
    before_run:
      - _pull_test_bundle
    steps:
      - xcode-test-without-building:
          title: Unit Tests
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UnitTests_iphonesimulator16.1.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UNIT_XCRESULT_PATH'

  run-tests-ui-1:
    meta:
      bitrise.io:
        machine_type_id: g2-m1.8core
    before_run:
      - _pull_test_bundle
    steps:
      - xcode-test-without-building:
          title: UI Test Suite 1
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests_iphonesimulator16.1-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_1_XCRESULT_PATH'

  run-tests-ui-2:
    meta:
      bitrise.io:
        machine_type_id: g2-m1.8core
    before_run:
      - _pull_test_bundle
    steps:
      - xcode-test-without-building:
          title: UI Test Suite 2
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-2_iphonesimulator16.1-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_2_XCRESULT_PATH'

  run-tests-ui-3:
    meta:
      bitrise.io:
        machine_type_id: g2-m1.8core
    before_run:
      - _pull_test_bundle
    steps:
      - xcode-test-without-building:
          title: UI Test Suite 3
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-3_iphonesimulator16.1-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_3_XCRESULT_PATH'

  deploy-test-results:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: run-test-groups\..*
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash
                set -eo pipefail

                xcrun xcresulttool merge "${BITRISE_UITESTS_1_XCRESULT_PATH}" "${BITRISE_UITESTS_2_XCRESULT_PATH}" "${BITRISE_UITESTS_3_XCRESULT_PATH}" "${BITRISE_UNIT_XCRESULT_PATH}"  --output-path "merged.xcresult"

                envman add --key BITRISE_XCRESULT_PATH --value "$(pwd)/merged.xcresult"
      - custom-test-results-export@0:
          inputs:
          - search_pattern: '*'
          - base_path: $BITRISE_XCRESULT_PATH
          - test_name: Pocket Tests
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_XCRESULT_PATH'
    after_run:
      - _danger

app:
  envs:
    - opts:
        is_expand: false
      BITRISE_PROJECT_PATH: Pocket.xcodeproj
    - opts:
        is_expand: false
      BITRISE_SCHEME: Pocket (iOS)
    - opts:
        is_expand: false
      BITRISE_EXPORT_METHOD: development
    - opts:
        is_expand: false
      SKIP_APOLLO_CODEGEN: '1'

meta:
  bitrise.io:
    machine_type_id: g2.4core
    stack: osx-xcode-14.1.x
