---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
  - push_branch: main
    pipeline: app-store-pipeline
  - pull_request_target_branch: develop
    pipeline: build-test-pipeline

pipelines:
  build-test-pipeline:
    stages:
      # Run the buld and test stage workflows
      - build: {}
      - test: {}
  app-store-pipeline:
    stages:
      # First Build the release build (app store build)
      - release-build: {}
      # Run the steps to deploy to the app store
      - deploy-app-store: {}
  nightly-internal-pipeline:
    stages:
      # First Build the release build (app store build)
      - release-build: {}
      # Run the steps to deploy to testflight internally
      - deploy-internal-testflight: {}
stages:
  build:
    workflows:
      - configure_build: {}
  test:
    workflows:
      # Run the test and qa build flow in parallel
      - test_1: {}
      #- test_2: {}
      #- test_3: {}
      #- qa-build: {}
  release-build:
    workflows:
      - release-build: {}
  deploy-internal-testflight:
    workflows:
      - internal-testflight-release: {}
  deploy-app-store:
    workflows:
      - app-store-release: {}

workflows:
  #Reusable workflow that is ran before each workflow to setup the necessary information
  _setup:
    steps:
      - brew-install@0:
          inputs:
            - packages: swiftlint
      - activate-ssh-key@4: {}
      - git-clone@6: {}
      - certificate-and-profile-installer@1: {}
      - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_XCCONFIG_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install production secrets.xcconfig
      - resource-archive@2:
          inputs:
            - extract_to_path: '$BITRISE_SOURCE_DIR/PocketKit/Sources/Textile/Style/Typography/Fonts'
            - archive_url: '$BITRISEIO_BASE_FONTS_URL'
          title: Install fonts
      - script@1:
          title: Download latest schema
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e

                cd PocketKit
                swift run ApolloCodegen download-schema
                swift run ApolloCodegen generate

  #Workflow to that can be ran after archiving builds to upload dysms to sentry.
  _upload_sentry:
    steps:
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e

                brew tap getsentry/tools
                brew install getsentry/tools/sentry-cli
                sentry-cli --log-level=debug --auth-token $SENTRY_AUTH_TOKEN  upload-dif -o pocket -p ios-next $BITRISE_DSYM_PATH
                #TODO: In the future we can add Sentry releases here.

  _danger:
    steps:
      - cache-pull@2: {}
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e

                cd PocketKit/

                echo "Run danger"
                swift run danger-swift ci
      - cache-push@2: {}

  #Builds a release build that could be uploaded to App Store Connect
  release-build:
    steps:
      - xcode-archive@4:
          title: Build an app store release build
          inputs:
            - project_path: '$BITRISE_PROJECT_PATH'
            - scheme: '$BITRISE_SCHEME'
            - distribution_method: app-store
            - configuration: RELEASE
            - xcconfig_content: CURRENT_PROJECT_VERSION = $BITRISE_BUILD_NUMBER
            - export_method: app-store
      - deploy-to-bitrise-io@2:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_IPA_PATH:BITRISE_IPA_PATH'
    before_run:
      - _setup
    after_run:
      - _upload_sentry

  # Uses artifacts from the release build stage and workflow to ship the build to testflight.
  internal-testflight-release:
    steps:
      - activate-ssh-key@4: {}
      #clone the repo so we can get our fastlane files.
      - git-clone@6: {}
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: release-build.release-build
      - fastlane@3:
          inputs:
            - connection: 'off'
            - api_key_path: '$BITRISEIO_APP_STORE_CONNECT_API_KEY_URL'
            - api_issuer: '$API_KEY_ISSUER_ID'
            - verbose_log: 'yes'
            - lane: beta_internal

  # Uses artifacts from the release build stage and workflow to ship the build to the App Store and create a github release.
  app-store-release:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: release-build.release-build
      - deploy-to-itunesconnect-deliver@2:
          inputs:
            - app_id: '$APP_ID'
            - connection: 'off'
            - api_key_path: '$BITRISEIO_APP_STORE_CONNECT_API_KEY_URL'
            - api_issuer: '$API_KEY_ISSUER_ID'
      - github-release@0:
          inputs:
            - username: '$GITHUB_RELEASE_USERNAME'
            - name: 8.0+$BITRISE_BUILD_NUMBER
            - body: '$GIT_CLONE_COMMIT_MESSAGE_SUBJECT'
            - pre_release: 'yes'
            - draft: 'no'
            - tag: 8.0+$BITRISE_BUILD_NUMBER
            - commit: '$GIT_CLONE_COMMIT_HASH'
            - api_token: '$GITHUB_RELEASE_TOKEN'

  qa-build:
    steps:
      - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_DEVELOPMENT_XCCONFIG_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install development secrets.xcconfig
      - xcode-archive@4:
          inputs:
            - xcconfig_content: |-
                COMPILER_INDEX_STORE_ENABLE = NO
                CURRENT_PROJECT_VERSION = $BITRISE_BUILD_NUMBER
            - configuration: Debug
      - deploy-to-bitrise-io@2: {}
      - slack@3:
          inputs:
            - channel: '#log-ios-qa-builds'
            - webhook_url: $SLACK_WEBHOOK_URL
    before_run:
      - _setup
    after_run:
      - _upload_sentry
  configure_build:
    steps:
    - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_TEST_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install test secrets.xcconfig
    - script@1.1:
        title: Build for Testing
        is_always_run: true
        inputs:
        - content: |
            set -euxo pipefail
            echo "-- build-for-testing --"
            mkdir DerivedData
            cp -r Tests\ iOS DerivedData
            xcodebuild "-project" "/Users/vagrant/git/Pocket.xcodeproj" "-scheme" "Pocket (iOS)" "CODE_SIGNING_ALLOWED=NO" -sdk "iphonesimulator" "-destination" "platform=iOS Simulator,name=iPhone 14,OS=latest" "COMPILER_INDEX_STORE_ENABLE=NO" "build-for-testing" "CODE_SIGN_IDENTITY=" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO" -derivedDataPath "/Users/vagrant/git/DerivedData" | xcpretty | tee xcodebuild_test.log
    - script@1.1:
        title: Compress Derived Data
        is_always_run: true
        inputs:
        - content: |
            set -euxo pipefail
            echo "-- compress --"
            exec zip -0 -qr "${BITRISE_SOURCE_DIR}/DerivedData.zip" \
            "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Debug_Test-iphonesimulator/Pocket.app" \
            "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Debug_Test-iphonesimulator/Tests\ iOS-Runner" \
            "$BITRISE_SOURCE_DIR/Pocket.xcodeproj" \
            "$BITRISE_SOURCE_DIR/UITests.xctestplan" \
            "$BITRISE_SOURCE_DIR/UITests-2.xctestplan" \
            "$BITRISE_SOURCE_DIR/UnitTests.xctestplan" \
            "$BITRISE_SOURCE_DIR/xcodebuild.log" \
            "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Debug_Test-iphonesimulator/" \
            "$BITRISE_SOURCE_DIR/Tests\ iOS/" \
            "$BITRISE_SOURCE_DIR/PocketKit/" \
    - deploy-to-bitrise-io@2:
        inputs:
        - deploy_path: "${BITRISE_SOURCE_DIR}/DerivedData.zip"
    before_run:
      - _setup
    after_run:
      #- _danger
  test_1:
    steps:
    - git::https://github.com/bitrise-steplib/bitrise-step-artifact-pull.git@main:
        title: Pull artifacts
        inputs:
        - verbose: true
        - artifact_sources: build.*
    - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_TEST_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install test secrets.xcconfig
    - script@1.1:
        title: Unzip
        inputs:
        - content: |
            set -euxo pipefail
            echo "$BITRISE_ARTIFACT_PATHS"
            echo "-- unzip -- "
            exec unzip "${BITRISE_ARTIFACT_PATHS}"
            echo "show dir"
            ls
    - script@1.1:
        title: Test without Building
        inputs:
        - content: |
            #!/usr/bin/env bash
            set -ex
            ls .
            ls ./Users/vagrant/git/
            #cp -r ./Users/vagrant/git/Tests\ iOS/* .
            mv ./Users/vagrant/git/* .
            ls -la
            echo "-- test-without-building --"
            xcodebuild -project "Pocket.xcodeproj" -scheme "Pocket (iOS)" -resultBundlePath "xcodebuild.xcresult" -derivedDataPath "/Users/vagrant/git/DerivedData" -testPlan "UITests" -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" test-without-building
    - custom-test-results-export@0:
        inputs:
        - search_pattern: "$BITRISE_SOURCE_DIR/xcodebuild.xcresult"
        - test_name: UITests
    - deploy-to-bitrise-io@2: {}
  test_2:
    steps:
      - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_TEST_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install test secrets.xcconfig
      - xcode-test@4:
          inputs:
            - destination: platform=iOS Simulator,name=iPhone 14,OS=latest
            - test_plan: UITests-2
      - deploy-to-bitrise-io@2: {}
    before_run:
      - _setup
    after_run:
      - _danger
  test_3:
    steps:
      - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_TEST_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install test secrets.xcconfig
      - xcode-test@4:
          inputs:
            - destination: platform=iOS Simulator,name=iPhone 14,OS=latest
            - test_plan: UnitTests
      - deploy-to-bitrise-io@2: {}
    before_run:
      - _setup
    after_run:
      - _danger

app:
  envs:
    - opts:
        is_expand: false
      BITRISE_PROJECT_PATH: Pocket.xcodeproj
    - opts:
        is_expand: false
      BITRISE_SCHEME: Pocket (iOS)
    - opts:
        is_expand: false
      BITRISE_EXPORT_METHOD: development
    - opts:
        is_expand: false
      SKIP_APOLLO_CODEGEN: '1'
meta:
  bitrise.io:
    machine_type_id: g2.4core
    stack: osx-xcode-14.0.x
