---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
trigger_map:
  - pull_request_target_branch: '*'
    pipeline: build-test-pipeline

pipelines:
  # Will create a build to test across multiple simulator devices
  build-test-pipeline:
    stages:
      # Build a test build in parallel
      - test-build: {}
      # Run multiple tests on simulators in parallel
      - run-test-groups: {}
      - deploy-test-results: {}
      # Build a debug build
      - debug-build: {}

  test-nightly-pipeline:
    stages:
      # Build a test build
      - test-build: {}
      # Run multiple tests on simulators in parallel
      - run-test-groups-nightly: {}
      - deploy-test-results-nightly: {}
    
  test-flakey-nightly-pipeline:
    stages:
      # Build a test build
      - test-build: {}
      # Run flakey tests
      - run-test-groups-flakey: {}
      # Deploy flakey test results
      - deploy-test-results-flakey: {}
  
  
  # Will create an app store capabale build, but release it to Internal Testing users in Testflight.
  # Intended to run nightly.
  nightly-internal-pipeline:
    stages:
      # First Build the release build (app store build)
      - release-build: {}
      # Run the steps to deploy to testflight internally
      - deploy-internal-testflight: {}
stages:
  test-build:
    workflows:
      # Build a test build
      - test-build: {}

  release-build:
    workflows:
      # Build a release build
      - release-build: {}

  debug-build:
    workflows:
      - debug-build: {}

  run-test-groups:
    workflows:
      - run-tests-unit: {}
      - run-tests-ui-1: {}
      - run-tests-ui-2: {}
      - run-tests-ui-3: {}
      - run-tests-ui-4: {}

  run-test-groups-flakey:
    workflows:
      - run-tests-flakey: {}

  deploy-test-results-flakey:
    should_always_run: true
    workflows:
      - deploy-test-results-flakey: {}

  run-test-groups-nightly:
    workflows:
      - run-tests-unit: {}
      - run-tests-ui-1: {}
      - run-tests-ui-2: {}
      - run-tests-ui-3: {}
      - run-tests-ui-4: {}
      # Turning off until iOS 16 is legacy
      # - run-tests-ui-1-legacy: {}
      # - run-tests-ui-2-legacy: {}
      # - run-tests-ui-3-legacy: {}
      # - run-tests-ui-4-legacy: {}

  deploy-test-results:
    should_always_run: true
    workflows:
      - deploy-test-results: {}

  deploy-test-results-nightly:
    should_always_run: true
    workflows:
      - deploy-test-results-nightly: {}

  release-build:
    workflows:
      - release-build: {}
  deploy-internal-testflight:
    workflows:
      - internal-testflight-release: {}

workflows:
  #Reusable workflow that is ran before each workflow to setup the necessary information
  _setup:
    steps:
      - brew-install@0:
          inputs:
            - packages: swiftlint
      - activate-ssh-key@4: {}
      - git-clone@7: {}
      - certificate-and-profile-installer@1: {}
      - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_XCCONFIG_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install production secrets.xcconfig
      - resource-archive@2:
          inputs:
            - extract_to_path: '$BITRISE_SOURCE_DIR/PocketKit/Sources/Textile/Style/Typography/Fonts'
            - archive_url: '$BITRISEIO_BASE_FONTS_URL'
          title: Install fonts
      - resource-archive@2:
          inputs:
            - extract_to_path: '$BITRISE_SOURCE_DIR/PocketKit/Sources/PocketStickerKit/Stickers'
            - archive_url: '$BITRISEIO_STICKERS_URL'
          title: Install stickers
      - script@1:
          title: Download latest schema
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e

                cd PocketKit
                swift package --allow-writing-to-package-directory apollo-cli-install
                ./apollo-ios-cli fetch-schema
                ./apollo-ios-cli generate

  #Workflow to that can be ran after archiving builds to upload dysms to sentry.
  _upload_sentry:
    steps:
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e

                brew tap getsentry/tools
                brew install getsentry/tools/sentry-cli
                sentry-cli --log-level=debug --auth-token $SENTRY_AUTH_TOKEN  upload-dif -o pocket -p ios-next $BITRISE_DSYM_PATH
                #TODO: In the future we can add Sentry releases here.

  _danger:
    steps:
      - activate-ssh-key@4: {}
      - git-clone@7: {}
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e

                echo "Run danger"
                swift run danger-swift ci

  # Helper step to pull the built test bundle.
  _pull_test_bundle:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: test-build.test-build

  # Helper step to install the last simulator version
  _install_past_ios:
    steps:
      - script@1:
          timeout: 600 # 10 minutes
          inputs:
            - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e
                
                brew tap robotsandpencils/made
                brew install robotsandpencils/made/xcodes
                
                echo "Install iOS 16 sim"
                sudo xcodes runtimes install "iOS 16.4"


  # Helper step to start snowplow
  _start_snowplow:
    steps:
        - script@1:
           timeout: 300 # 5 minutes
           inputs:
             - content: |
                #!/usr/bin/env bash

                # fail if any commands fails
                set -e
                
                ## Usually Pocket runs snowplow via our docker image, but Bitrise does not support docker in Mac environments so we use their built jar.
                ## It uses the values in MICRO_IGLU_REGISTRY_URL and MICRO_IGLU_API_KEY
                echo "Run snowplow"
                brew install wget openjdk
                wget https://github.com/snowplow-incubator/snowplow-micro/releases/download/micro-1.7.2/snowplow-micro-1.7.2.jar
                java -jar snowplow-micro-1.7.2.jar &

  #Builds a release build that could be uploaded to App Store Connect
  release-build:
    steps:
      - restore-spm-cache@1: {}
      - xcode-archive@4:
          title: Build an app store release build
          inputs:
            - project_path: '$BITRISE_PROJECT_PATH'
            - scheme: '$BITRISE_SCHEME'
            - distribution_method: app-store
            - configuration: Release
            - xcconfig_content: CURRENT_PROJECT_VERSION = $BITRISE_BUILD_NUMBER
            - export_method: app-store
      - save-spm-cache@1: {}
      - deploy-to-bitrise-io@2: {}
      - deploy-to-bitrise-io@2:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_IPA_PATH:BITRISE_IPA_PATH'
    before_run:
      - _setup
    after_run:
      - _upload_sentry

  # Uses artifacts from the release build stage and workflow to ship the build to testflight.
  internal-testflight-release:
    steps:
      - activate-ssh-key@4: {}
      #clone the repo so we can get our fastlane files.
      - git-clone@6: {}
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: release-build.release-build
      - fastlane@3:
          inputs:
            - verbose_log: 'yes'
            - lane: beta_internal

  test-build:
    steps:
      - file-downloader@1:
          inputs:
            - source: '$BITRISEIO_SECRETS_TEST_URL'
            - destination: '$BITRISE_SOURCE_DIR/Config/secrets.xcconfig'
          title: Install test secrets.xcconfig
      - restore-spm-cache@1: {}
      - xcode-build-for-test:
          inputs:
            - destination: generic/platform=iOS Simulator
      - save-spm-cache@1: {}
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_TEST_BUNDLE_PATH:BITRISE_TEST_BUNDLE_PATH'
    before_run:
      - _setup

  run-tests-unit:
    before_run:
      - _pull_test_bundle
    steps:
      - xcode-test-without-building:
          timeout: 600 #10 minutes
          title: Unit Tests
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UnitTests_iphonesimulator17.0.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 15,OS=17.0.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UNIT_XCRESULT_PATH'

  debug-build:
    steps:
    - file-downloader@1:
        inputs:
        - source: $BITRISEIO_SECRETS_DEVELOPMENT_XCCONFIG_URL
        - destination: $BITRISE_SOURCE_DIR/Config/secrets.xcconfig
        title: Install development secrets.xcconfig
    - fastlane@3:
        inputs:
        - lane: debug_build
    - deploy-to-bitrise-io@2: {}
    before_run:
    - _setup

  run-tests-ui-1:
    before_run:
      - _pull_test_bundle
      - _start_snowplow
    steps:
      - xcode-test-without-building:
          timeout: 1200 #20 minutes
          title: UI Test Suite 1
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-1_iphonesimulator17.0-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 15,OS=17.0.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_1_XCRESULT_PATH'

  run-tests-ui-2:
    before_run:
      - _pull_test_bundle
      - _start_snowplow
    steps:
      - xcode-test-without-building:
          timeout: 1200 #20 minutes
          title: UI Test Suite 2
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-2_iphonesimulator17.0-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 15,OS=17.0.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_2_XCRESULT_PATH'

  run-tests-ui-3:
    before_run:
      - _pull_test_bundle
      - _start_snowplow
    steps:
      - xcode-test-without-building:
          timeout: 1200 #20 minutes
          title: UI Test Suite 3
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-3_iphonesimulator17.0-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 15,OS=17.0.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_3_XCRESULT_PATH'

  run-tests-ui-4:
    before_run:
      - _pull_test_bundle
      - _start_snowplow
    steps:
      - xcode-test-without-building:
          timeout: 1200 #20 minutes
          title: UI Test Suite 4
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-4_iphonesimulator17.0-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 15,OS=17.0.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_4_XCRESULT_PATH'


  run-tests-ui-1-legacy:
    before_run:
      - _install_past_ios
      - _pull_test_bundle
      - _start_snowplow
    steps:
      - xcode-test-without-building:
          timeout: 1200 #20 minutes
          title: UI Test Suite 1 Legacy
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-1_iphonesimulator17.0-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16.4
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_1_LEGACY_XCRESULT_PATH'

  run-tests-ui-2-legacy:
    before_run:
      - _install_past_ios
      - _pull_test_bundle
      - _start_snowplow
    steps:
      - xcode-test-without-building:
          timeout: 1200 #20 minutes
          title: UI Test Suite 2 Legacy
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-2_iphonesimulator17.0-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16.4
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_2_LEGACY_XCRESULT_PATH'

  run-tests-ui-3-legacy:
    before_run:
      - _install_past_ios
      - _pull_test_bundle
      - _start_snowplow
    steps:
      - xcode-test-without-building:
          timeout: 1200 #20 minutes
          title: UI Test Suite 3 Legacy
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-3_iphonesimulator17.0-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16.4
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_3_LEGACY_XCRESULT_PATH'

  run-tests-ui-4-legacy:
    before_run:
      - _install_past_ios
      - _pull_test_bundle
      - _start_snowplow
    steps:
      - xcode-test-without-building:
          timeout: 1200 #20 minutes
          title: UI Test Suite 4 Legacy
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITests-4_iphonesimulator17.0-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16.4
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_4_LEGACY_XCRESULT_PATH'

  run-tests-flakey:
    before_run:
      - _pull_test_bundle
      - _start_snowplow
    steps:
      - xcode-test-without-building:
          timeout: 600 #10 minutes
          title: Unit Tests
          inputs:
            - xctestrun: '${BITRISE_TEST_BUNDLE_PATH}/Pocket (iOS)_UITestsFlaky_iphonesimulator17.0-arm64-x86_64.xctestrun'
            - destination: platform=iOS Simulator,name=iPhone 15,OS=17.0.1
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTSFLAKEY_XCRESULT_PATH'

  deploy-test-results:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: run-test-groups\..*
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash
                set -eo pipefail

                xcrun xcresulttool merge "${BITRISE_UITESTS_1_XCRESULT_PATH}" "${BITRISE_UITESTS_2_XCRESULT_PATH}" "${BITRISE_UITESTS_3_XCRESULT_PATH}" "${BITRISE_UITESTS_4_XCRESULT_PATH}" "${BITRISE_UNIT_XCRESULT_PATH}"  --output-path "merged.xcresult"
                envman add --key BITRISE_XCRESULT_PATH --value "$(pwd)/merged.xcresult"

      - custom-test-results-export@0:
          inputs:
            - search_pattern: '*'
            - base_path: $BITRISE_XCRESULT_PATH
            - test_name: Pocket Tests
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_XCRESULT_PATH'
    after_run:
      - _danger

  deploy-test-results-nightly:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: run-test-groups-nightly\..*
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash
                set -eo pipefail

                # Switch to this when legacy is turned back on
                # xcrun xcresulttool merge "${BITRISE_UITESTS_1_XCRESULT_PATH}" "${BITRISE_UITESTS_2_XCRESULT_PATH}" "${BITRISE_UITESTS_3_XCRESULT_PATH}" "${BITRISE_UITESTS_4_XCRESULT_PATH}" "${BITRISE_UITESTS_1_LEGACY_XCRESULT_PATH}" "${BITRISE_UITESTS_2_LEGACY_XCRESULT_PATH}" "${BITRISE_UITESTS_3_LEGACY_XCRESULT_PATH}" "${BITRISE_UITESTS_4_LEGACY_XCRESULT_PATH}" "${BITRISE_UNIT_XCRESULT_PATH}"  --output-path "merged.xcresult"

                xcrun xcresulttool merge "${BITRISE_UITESTS_1_XCRESULT_PATH}" "${BITRISE_UITESTS_2_XCRESULT_PATH}" "${BITRISE_UITESTS_3_XCRESULT_PATH}" "${BITRISE_UITESTS_4_XCRESULT_PATH}" "${BITRISE_UNIT_XCRESULT_PATH}"  --output-path "merged.xcresult"

                envman add --key BITRISE_XCRESULT_PATH --value "$(pwd)/merged.xcresult"
      - custom-test-results-export@0:
          inputs:
            - search_pattern: '*'
            - base_path: $BITRISE_XCRESULT_PATH
            - test_name: Pocket Tests
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_XCRESULT_PATH'

  deploy-test-results-flakey:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: run-test-groups-nightly-flakey\..*
      - script@1:
          inputs:
            - content: |
                #!/usr/bin/env bash
                set -eo pipefail

                envman add --key BITRISE_XCRESULT_PATH --value "${BITRISE_UITESTSFLAKEY_XCRESULT_PATH}"
      - custom-test-results-export@0:
          inputs:
            - search_pattern: '*'
            - base_path: $BITRISE_XCRESULT_PATH
            - test_name: Pocket Tests
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_XCRESULT_PATH'

app:
  envs:
    - opts:
        is_expand: false
      BITRISE_PROJECT_PATH: Pocket.xcodeproj
    - opts:
        is_expand: false
      BITRISE_SCHEME: Pocket (iOS)
    - opts:
        is_expand: false
      BITRISE_EXPORT_METHOD: development
    - opts:
        is_expand: false
      SKIP_APOLLO_CODEGEN: '1'

meta:
  bitrise.io:
    machine_type_id: g2-m1-max.10core
    stack: osx-xcode-15.0.x
