// @generated
// This file was automatically generated and should not be edited.

@_exported import ApolloAPI

public class ResolveItemUrlQuery: GraphQLQuery {
  public static let operationName: String = "ResolveItemUrl"
  public static let operationDocument: ApolloAPI.OperationDocument = .init(
    definition: .init(
      #"query ResolveItemUrl($url: String!) { itemByUrl(url: $url) { __typename givenUrl normalUrl resolvedUrl savedItem { __typename url id } } }"#
    ))

  public var url: String

  public init(url: String) {
    self.url = url
  }

  public var __variables: Variables? { ["url": url] }

  public struct Data: PocketGraph.SelectionSet {
    public let __data: DataDict
    public init(_dataDict: DataDict) { __data = _dataDict }

    public static var __parentType: ApolloAPI.ParentType { PocketGraph.Objects.Query }
    public static var __selections: [ApolloAPI.Selection] { [
      .field("itemByUrl", ItemByUrl?.self, arguments: ["url": .variable("url")]),
    ] }

    /// Look up Item info by a url.
    public var itemByUrl: ItemByUrl? { __data["itemByUrl"] }

    /// ItemByUrl
    ///
    /// Parent Type: `Item`
    public struct ItemByUrl: PocketGraph.SelectionSet {
      public let __data: DataDict
      public init(_dataDict: DataDict) { __data = _dataDict }

      public static var __parentType: ApolloAPI.ParentType { PocketGraph.Objects.Item }
      public static var __selections: [ApolloAPI.Selection] { [
        .field("__typename", String.self),
        .field("givenUrl", PocketGraph.Url.self),
        .field("normalUrl", String.self),
        .field("resolvedUrl", PocketGraph.Url?.self),
        .field("savedItem", SavedItem?.self),
      ] }

      /// key field to identify the Item entity in the Parser service
      public var givenUrl: PocketGraph.Url { __data["givenUrl"] }
      /// A normalized value of the givenUrl.
      /// It will look like a url but is not guaranteed to be a valid url, just a unique string that is used to eliminate common duplicates.
      /// Item's that share a normal_url should be considered the same item. For example https://getpocket.com and http://getpocket.com will be considered the same since they both normalize to http://getpocket.com
      /// This is technically the true identity of an item, since this is what the backend uses to tell if two items are the same.
      /// However, for the clients to use this, they would all have to ship an implementation of the normalization function that the backend has exactly.
      /// And even if it did that, some items, some of the earliest saves, use a legacy normalize function and the client would have no way to know when to use which normalizing function.
      public var normalUrl: String { __data["normalUrl"] }
      /// If the givenUrl redirects (once or many times), this is the final url. Otherwise, same as givenUrl
      public var resolvedUrl: PocketGraph.Url? { __data["resolvedUrl"] }
      /// Helper property to identify if the given item is in the user's list
      public var savedItem: SavedItem? { __data["savedItem"] }

      /// ItemByUrl.SavedItem
      ///
      /// Parent Type: `SavedItem`
      public struct SavedItem: PocketGraph.SelectionSet {
        public let __data: DataDict
        public init(_dataDict: DataDict) { __data = _dataDict }

        public static var __parentType: ApolloAPI.ParentType { PocketGraph.Objects.SavedItem }
        public static var __selections: [ApolloAPI.Selection] { [
          .field("__typename", String.self),
          .field("url", String.self),
          .field("id", PocketGraph.ID.self),
        ] }

        /// The url the user saved to their list
        public var url: String { __data["url"] }
        /// Surrogate primary key. This is usually generated by clients, but will be generated by the server if not passed through creation
        public var id: PocketGraph.ID { __data["id"] }
      }
    }
  }
}
