//
//  PKTHighlightAnnotation.h
//  Pocket
//
//  Created by Nicholas Zeltzer on 4/2/18.
//

@import Foundation;

#import "PKTModelCodable.h"
#import "PKTKusari.h"

@interface PKTHighlightAnnotation : NSObject <PKTModelCodable>

/// @return String representation of the patch's format version
@property (nonnull, nonatomic, readonly, copy) NSString *versionString;
/// @return The PKTItem ID of the PKTItem this annotation belongs to.
@property (nonnull, nonatomic, readonly, copy) NSString *itemID;
/// @return The UUID of this annotation
/// @note Generated by the client when the annotation is first created.
@property (nonnull, nonatomic, readonly, copy) NSString *annotationID;
/// @return NSString representation of the annotated text
@property (nonnull, nonatomic, readonly, copy) NSString *quote;
/// @return The patch object that represents where the annotation was created within the context of the original text content.
/// @note This patch is intended to be unambiguious and resilient against changes to the Item's body text.
@property (nonnull, nonatomic, readonly, copy) NSString *patch;
/// @return NSDate representation of the time when this annotation was created
@property (nonnull, nonatomic, readonly, copy) NSDate *created;
// @return NSInteger representation of the patch's format version
@property (nonatomic, readonly, assign) NSInteger version;
/// @return NSString representation of the local unique ID.
/// @note This value may be nil; use of itemID is preferred
@property (nonnull, nonatomic, readonly, copy) NSString *uniqueID;
/// @return NSDate representation of the time when this annotation was modified
@property (nullable, nonatomic, readonly, copy) NSDate *modified;
/// @return The User ID of the PKTItem this annotation belongs to
@property (nullable, nonatomic, readonly, copy) NSString *userID;

@property (nullable, nonatomic, readonly) NSData *JSONData;
@property (nullable, nonatomic, readonly) NSDictionary<NSString*, NSString*> *JSONObject;
@property (nullable, nonatomic, readonly) NSString *JSONString;

+ (nullable PKTHighlightAnnotation *)newAnnotationWithData:(nonnull NSData*)JSONData;

+ (nullable PKTHighlightAnnotation *)newAnnotationWithJSONObject:(nonnull NSDictionary<NSString*, id>*)JSONObject;

+ (nonnull NSDateFormatter *)dateFormatter;

- (nullable NSData *)JSONData;

- (nullable NSDictionary *)JSONObject;

- (nullable NSString *)JSONString;

@end

@interface PKTHighlightAnnotation (PKTListDiffable) <PKTListDiffable>

@end
