# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

BITRISE_IPA_PATH = ENV["BITRISE_IPA_PATH"]
APPLE_ID = ENV["APP_ID"]
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight Internal Testers via CI"
  lane :beta_internal do

    #upload to testflight for our internal apps store connect nightly builds.
    upload_to_testflight(
      apple_id: APPLE_ID,
      skip_waiting_for_build_processing: false,
      groups: ['Nightly Internal Builds'],
      submit_beta_review: false,
      ipa: BITRISE_IPA_PATH,
      expire_previous_builds: true
    )
  end
end
